              <div id="productbartabs">
               <ul class="css-tabs">
	<li><a href="#tab1">DESCRIPTION</a></li>
	<li><a href="#tab2">SUPPLEMENT FACTS</a></li>
	<li><a href="#tab3">Q & A</a></li>
    <li><a href="#tab4">RELATED</a></li>
    <li><a href="#tab5">TESTIMONIALS</a></li>
</ul>

<!-- tab "panes" -->
<div class="css-panes">
	<div id="tab1">

<h2>Integrated Supplements 100% Creapure Creatine</h2>   

<p>For decades, athletes and workout enthusiasts have used creatine monohydrate to improve, strength, power, endurance, and as an aid to muscle growth and recovery.</p> 
<p>In fact, creatine monohydrate is the only sports nutrition product that has proven itself in hundreds of clinical studies spanning over three decades.  In an industry plagued by hype and false promises, creatine monohydrate stands alone as a uniquely powerful, natural, cost&#45;effective, and safe performance&#45;enhancing nutrient.</p> 
<p>However, all creatine monohydrate is not created equal.  Potentially harmful impurities such as dicyandiamide, thiourea, and dihydrotriazine may be present in creatine products produced via some low&#45;cost methods. And because many supplement companies simply use the cheapest creatine they can find, quality often varies widely from one brand of creatine to the next.</p> 
<p>This is why Integrated Supplements creatine monohydrate contains 100% Creapure<sup>&reg;</sup>.  Only Creapure<sup>&reg;</sup> is produced using a unique patented process (U.S. patent 5,719,319) which guarantees the highest purity, and potency. Each batch is produced using Good Manufacturing Practices (GMPs) in an FDA&#45;registered plant in Trostberg, Germany and is rigorously tested using state&#45;of&#45;the art high pressure liquid chromatography (HPLC).</p>   


    </div><!--Close first Pane-->

    <div id="tab2"><h2>100% Creapure<sup>&reg;</sup>Creatine</h2><img src="Images/SupplementFacts/JPEGS/SFC.jpg" /></div>
	<div id="tab3">

<p> For a more in-depth Creatine Q&amp;A, click <a href="intsup0013.CREATINEQA">here</a></p>  
    
<h2>Q. What is creatine?</h2>
<p><font color="be1622"><strong> A. </strong> </font>Creatine is an energy&#45;related nutrient formed in the body from the amino acids arginine, methionine, and glycine. Creatine is directly involved in a process which allows our bodies to rapidly regenerate the energy molecule known as adenosine triphosphate, or ATP. Under periods of high energy demand or physical exertion, the amount of work (both physical and mental) we are able to perform is often limited by our bodies&#39; ability to rapidly regenerate ATP. </p>
<p> As creatine plays such an important role in energy production, creatine supplements have been widely embraced by athletes (especially athletes whose sports require quick bursts of energy and muscular strength, like weightlifters, bodybuilders, sprinters, or football players). But it&#39;s <strong><em>very</em></strong> important to realize that creatine supplementation is likely to benefit <strong><em>all</em></strong> types of individuals, including those not usually associated with creatine usage. As the research on creatine continues to accumulate, we&#39;re seeing that diverse groups, including females, the elderly, and those simply looking to prevent the ravages of aging, can all benefit greatly from optimizing their creatine intake through supplementation. </p>
<p> To state fact simply, the stigma of creatine as a mere &ldquo;bodybuilding&rdquo; supplement <strong><em>must</em></strong> end if the larger population of health&#45;conscious individuals are to reap the full benefits of this remarkable substance. </p>
<p> Along these lines, because creatine has often been deemed guilty by association with other performance&#45;enhancing substances, it&#39;s important to state not only what creatine is, but what it <strong><em>isn&#39;t</em></strong>. Despite the impression which can be garnered from the mainstream media coverage of creatine, creatine is <strong><em>not</em></strong> a steroid hormone, creatine is <strong><em>not</em></strong> a hormone&#45;percursor, and creatine use is <strong><em>not </em></strong>banned by any major athletic association or government agency in the United States. </p>
<p> Our body, in fact, produces creatine, and creatine is also found in our diet, in foods such as meat or fish. Our goal with supplementing creatine (as is our goal with supplementing other nutrients) is simply to maximize our intake without having to consume massive amounts of food.</p>
 
 <h2>Q. How does creatine work?</h2> 
 
 <p> <font color="be1622"><strong> A. </strong> </font>In order to grasp how creatine works, it&#39;s helpful to think of creatine as a sort of &ldquo;emergency&rdquo; energy substrate &#45; an energy substrate which the body can call upon to produce energy very quickly without having to start up the entire &ldquo;assembly line&rdquo; involved in producing energy from carbohydrates or fats. </p>
<p> Metabolically speaking, this emergency energy makes creatine a very valuable substance, but unlike carbohydrates or fats (of which we have, essentially, an inexhaustible amount), our reserves of creatine are often in relatively short supply. This is why the most demanding sort of muscular activity, like lifting heavy weights, can only be sustained for short periods of time. </p>
<p> Looking at the matter from an evolutionary perspective it&#39;s not surprising that the most &ldquo;valued&rdquo; tissues of the body, like the brain, skeletal muscles, and heart, have a notably high ability to produce energy quickly (in the form of ATP) from a process involving creatine. </p>
<p> And, knowing this, it makes sense that creatine supplementation has shown promise in disorders involving the brain, heart, and musculature. Again, it&#39;s become clear in recent years that creatine is <strong><em>far</em></strong> more than simply a muscle&#45;builder. More than likely, it&#39;s a substance which can benefit our overall health on a <strong><em>very</em></strong> fundamental level. </p>
<p> In a technical sense, creatine, which is stored in the body as <em>creatine phosphate</em>, [also known as <em>phosphocreatine</em> (CrP)] is able to donate phosphate, and rapidly recycle the energy molecule, ATP. </p>
<p> On a cellular level, energy is produced when ATP splits and releases one of its phosphate groups (becoming ADP, or adenosine <strong><em>di</em></strong>phosphate in the process). Phosphocreatine is able to rapidly regenerate ATP from ADP, much like the recharging of a battery. In muscles, the rapidity of this energy regeneration is responsible for maximal power output, and this helps to explain why creatine has become so popular with strength and power athletes.</p>

<h2>Q. What can an athlete or workout&#45;enthusiast expect to notice from taking creatine supplements?</h2>

<p><font color="be1622"><strong> A. </strong></font> Athletes almost universally notice an increase in their explosive strength and muscular endurance from taking creatine. This means that a sprinter could notice increased speed and better performance, or a weightlifter could lift heavier weights, or that a bodybuilder could increase strength, and train at a higher level throughout a workout. </p>
<p> Football and hockey players may notice more explosive starts and less fatigue, while baseball players may notice that they get a better jump on the ball in the field, and a more powerful swing at the plate. </p>
<p> Taken long&#45;term, creatine may also help to create a better cellular environment for enhanced muscular growth and recovery, which is always an added bonus in strength and power sports. </p>
<p> The jury&#39;s still out on the benefits of creatine use for endurance athletes like marathoners, and tri&#45;athletes, however. The type of explosive energy to which creatine contributes is thought to be of lesser value in these sports. Where creatine can improve the <em>anaerobic</em> production of energy, endurance athletics are commonly thought to engage the <em>aerobic</em> sub&#45;segment of energy production which doesn&#39;t utilize the creatine phosphate system all that much. </p>
<p> Of course, the aerobic/anaerobic distinction is somewhat over&#45;simplified &#45; it&#39;s not really a black&#45;or&#45;white phenomenon. No activity engages <strong><em>solely</em></strong> one type of energy production at the expense of others, and as such, creatine <strong><em>has</em></strong> been found to offer some <strong><em>unique</em></strong> benefits to endurance athletes. </p>
<p> Creatine may potentially be able to spare muscle glycogen, the carbohydrate fuel source of working muscles, thus making more glycogen available in the latter stages of training. </p>
<p> Researchers have also noted that short bursts of explosive energy (the kind creatine <strong><em>does</em></strong> help with) are of increasing importance in competitive endurance sports. An athlete who has the ability to intersperse short bursts of explosive speed into his or her race has a distinct edge on the competition, and this is another area where creatine delivers for endurance athletes:</p>
<p> <a href="http://www.acsm-msse.org/pt/re/msse/abstract.00005768-199807000-00016.htm;jsessionid=JszGhxyQ25tn7JGHJMYhcLcBpQnMdpb8Q1l2vCGvpMv2XPJ1Q0Bt!-620876979!181195629!8091!-1" target="_blank">Study Link &#45; Creatine supplementation in endurance sports.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> We conclude that creatine supplementation at doses of 6 g daily has positive effects on short&#45;term exercise included into aerobic endurance exercise.</blockquote></em></p>
<p> Creatine could also indirectly benefit endurance athletes because of its remarkable effects on reducing exercise&#45;induced inflammatory damage, and improving muscular recovery. </p>
<p> Researchers have found that creatine supplementation (5 grams taken 4 times per day) for 5 days prior to a 30 kilometer run significantly reduced several markers of tissue damage and inflammation in experienced distance runners:</p>
<p> <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T99-4CYR0C1-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=ee4b2574ed13089cc260dbd9c6ccc41f" target="_blank">Study Link &#45; The effect of creatine supplementation upon inflammatory and muscle soreness markers after a 30km race.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> Pre&#45;race blood samples were collected immediately before running the 30km, and 24h after the end of the test (the post&#45;race samples). After the test, athletes from the control group presented an increase in plasma CK (4.4&#45;fold), LDH (43%), PGE2 6.6&#45;fold) and TNF&#45;</em><em> &alpha; (</em><em> 2.34&#45;fold) concentrations, indicating a high level of cell injury and inflammation. Creatine supplementation attenuated the changes observed for CK (by 19%), PGE2 and TNF&#45;</em><em> &alpha; (</em><em> by 60.9% and 33.7%, respectively, p&lt;0.05) and abolished the increase in LDH plasma concentration observed after running 30km.</blockquote></em></p>
<p> The runners in the above study reported no side&#45;effects from creatine use (even at what could be considered a relatively substantial dose), and their race completion times were unaffected. </p>
<p> Because it&#39;s so important for athletes to find safe ways to keep inflammation and tissue damage to a minimum, creatine use certainly deserves some serious consideration by <strong><em>all</em></strong> types of athletes and fitness enthusiasts. Even if it doesn&#39;t immediately improve performance, moderate doses of creatine have the potential to significantly shorten recovery time after races and between workouts which, in the long&#45;run is certain to be of significant benefit.</p>

<h2>Q. Can creatine supplementation benefit non&#45;athletes and sedentary individuals?</h2>
<p><font color="be1622"><strong> A.</strong></font> It seems likely that it can &#45; and by several different mechanisms, at that. The anti&#45;inflammatory effect exhibited in the above study is a clue that creatine may have beneficial effects in reducing oxidative stress (which we&#39;ve written about in previous newsletters). We also saw in our nitric oxide newsletters, how creatine may be able to reduce levels of the suspected cardiovascular toxin, known as homocysteine. In fact, knowing how creatine works, and how important proper energy production is to the health of the bodies most valued tissues, creatine is likely to be one of the most effective anti&#45;aging supplements we have at our disposal. </p>
<p> As a potential anti&#45;aging compound, creatine supplementation has begun to be studied in aging adults. While the research isn&#39;t conclusive at this point, even creatine&#39;s &ldquo;mere&rdquo; ability to increase muscular strength and recovery appears to be of unique benefit to older individuals. </p>
<p> For young people, building muscle mass is often viewed merely as a means to improve athletic performance, or, to improve the aesthetic appeal of ones physique. But the gradual loss of muscle mass and function which often accompanies old age is, in fact, a life&#45;threatening medical problem. </p>
<p> As such, researchers wondered if creatine&#39;s benefits, which are now very well&#45;documented in younger athletes, would translate to improving muscle mass and strength in older individuals as well. </p>
<p> Increasingly, research is beginning to show that it may. Studies conducted with both eldery men and elderly women have found strength, and the ability to perform functional living tasks to improve with creatine supplementation.</p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/11880821?ordinalpos=1&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_DiscoveryPanel.Pubmed_Discovery_RA&linkpos=1&log$=relatedarticles&logdbfrom=pubme" target="_blank">Study Link &#45; Creatine supplementation improves muscular performance in older men.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> These data indicate that 7 d of creatine supplementation is effective at increasing several indices of muscle performance, including functional tests in older men without adverse side effects. Creatine supplementation may be a useful therapeutic strategy for older adults to attenuate loss in muscle strength and performance of functional living tasks.</blockquote></em></p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/17943308?ordinalpos=1&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_DiscoveryPanel.Pubmed_Discovery_RA&linkpos=3&log$=relatedarticles&logdbfrom=pubmed" target="_blank">Study Link &#45; Creatine supplementation improves muscular performance in older women.</a></p>
<p> Quote from the above study:</p>
<blockquote><p><em> Short&#45;term creatine supplementation resulted in an increase in strength, power, and lower&#45;body motor functional performance in older women without any adverse side effects.</blockquote></em></p>
<p> So, even though creatine is commonly thought of as a supplement to improve power for athletic performance, the fact that creatine improves energy production at a very fundamental level makes it apt to benefit people at every stage of life. Of course, in the elderly, an increase in muscular strength and power output may manifest in something as simple as being able to get out of a chair without assistance, or being able to climb a flight of stairs; but maintaining or regaining the ability to perform such simple tasks can have truly life&#45;altering implications. If creatine delivers in this regard, as research indicates it may, the days of creatine&#39;s stigma as a mere bodybuilding supplement should be numbered.</p>

<h2>Q. If creatine improves energy production at a fundamental level, can creatine offer benefits outside of the muscular system?</h2>
<p><font color="be1622"><strong> A. </strong></font> Yes. Where creatine is a nutrient utilized by various tissues, it&#39;s no surprise that the benefits noticed from creatine aren&#39;t just limited to our muscles. For example, in recent years, creatine&#39;s role in improving <strong><em>mental</em></strong> function has begun to be explored as well. </p>
<p> One of the most compelling studies in this regard was conducted by researchers from the University of Tokyo, and was published in the journal, <em>Neuroscience Research</em>, in 2002. </p>
<p> The researchers found that creatine supplementation (8 grams per day for 5 days) significantly reduced the mental fatigue associated with performing repeated mathematical calculations. </p>
<p> Participants in the study were asked to perform a test of mental functioning known as the Uchida&#45;Kraepelin test; in which subjects are asked to calculate the addition of random numbers over a 15&#45;minute period, take a five minute rest, then perform the test for another 15 minutes. </p>
<p> In the Uchida&#45;Kraeplin test, it&#39;s commonly found that after the 5&#45;minute rest period, test scores initially increase slightly relative to the end of the first 15&#45;minute period, only to rapidly decline soon thereafter as a result of mental fatigue. </p>
<p> The researchers who conducted the following study, however, found that creatine consumption was able to increase test scores relative to the placebo group in both the first and second 15&#45;minute intervals of the test. <strong><em>Creatine appeared to be particularly effective in preventing the drop&#45;off in test performance during the second interval, and thus appears to significantly delay mental fatigue.</em></strong></p>
<p> The researchers also noted a reduction of oxygenated hemoglobin in the brains of the subjects taking creatine which could imply improved oxygenation of the brain, or possibly a reduced requirement for oxygen in the presence of creatine:</p>
<p> <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T0H-454TR73-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=b2f9124a7c47e849ead6b07eb9974954" target="_blank">Study Link &#45; Effects of creatine on mental fatigue and cerebral hemoglobin oxygenation.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> Using double&#45;blind placebo&#45;controlled paradigm, we demonstrated that dietary supplement of creatine (8 g/day for 5 days) reduces mental fatigue when subjects repeatedly perform a simple mathematical calculation. After taking the creatine supplement, task&#45;evoked increase of cerebral oxygenated hemoglobin in the brains of subjects measured by near infrared spectroscopy was significantly reduced, which is compatible with increased oxygen utilization in the brain.</blockquote></em></p>
<p> Another notable study on creatine and brain function found an improvement in working memory and intelligence in vegetarians taking 5 grams of creatine daily for six weeks (vegetarians consume less creatine than meat&#45;eaters, therefore, the effects of creatine supplementation are often more pronounced in vegetarians).</p>
<p> <a href="http://journals.royalsociety.org/content/995yme1nnn6qvya1/fulltext.pdf" target="_blank">Study Link &#45; Oral creatine monohydrate supplementation improves brain performance: a double&#45;blind, placebo&#45;controlled, cross&#45;over trial.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> Creatine supplementation had a significant positive effect (p &lt; 0.0001) on both working memory (backward digit span) and intelligence (Raven''s Advanced Progressive Matrices), both tasks that require speed of processing. These findings underline a dynamic and significant role of brain energy capacity in influencing brain performance.</blockquote></em></p>
<p> Recent research has also found that creatine may be able to slow the neurological decline associated with aging. And because overall aging and neurodegeneration are so closely related, it has been proposed that <strong><em>creatine supplementation may even extend healthy lifespan.</em></strong></p>
<p> In a very recent study conducted with mice, researchers from the University of Munich found that creatine supplementation led to a 9% increase in average healthy lifespan, and significantly improved performance on neurobehavioral tests. In the study, creatine was found to reduce markers of oxidative stress and interestingly, creatine significantly reuduced the formation of the age pigment, lipofucsin (lipofuscin can be noticed on the skin in the form of unsightly &ldquo;age spots&rdquo; or &ldquo;liver spots,&rdquo; but its presence in <strong><em>all</em></strong> tissues, including the brain, is a clear marker of the degeneration of aging). </p>
<p> It&#39;s really amazing to think that a simple, safe, and economical supplement like creatine, in addition to its effects on muscular function, may also be able to improve mental function, intelligence, and neurological health as well. But as we at Integrated Supplements have been saying for some time, when we improve the ability of the cells to produce energy efficiently, the result is a remarkable improvement in every conceivable bodily function and aspect of health. The far&#45;reaching benefits of creatine are yet another testament to the validity of this approach.</p>




<h2> Q. Creatine detractors say that creatine simply causes the cells of the body to hold more water, and that it&#39;s this effect which is responsible for creatine&#39;s effect on muscles. Some people are concerned that any effects they notice from taking creatine will be short&#45;lived, and will disappear soon after creatine use is discontinued. Is there any validity to this line of thinking?</h2>
<p><font color="be1622"><strong> A. </strong></font> Not really. As we&#39;ve seen, creatine is primarily an energy molecule, and creatine primarily works by allowing the cells (of various tissues) to produce energy more efficiently. For athletes undergoing weight training this means increases in muscle strength, and ultimately, muscle size. </p>
<p> It is true that creatine can add to the water&#45;volume inside muscle cells &#45; and this phenomenon may have much to do with the initial weight gain some people notice when taking creatine. But to say that creatine &ldquo;just&rdquo; causes the cells to hold more water, or to imply that creatine&#39;s benefits are short&#45;lived or superficial is downright ridiculous. </p>       
<p> But unfortunately, this is precisely the type of misinformation that is often heard from the ill&#45;informed, self&#45;proclaimed experts who take it upon themselves to (knowingly or not) disseminate falsehoods and lies about creatine. </p>
<p> The fact is that no single nutritional substance has been shown, in more peer&#45;reveiwed, double&#45;blind studies, to be more effective than creatine for increasing muscle power, strength and recovery. And some studies have shown, despite the pervasive myth to the contrary, that lean tissue mass and strength are <strong><em>maintained</em></strong> in exercising individuals, <strong><em>months</em></strong> after creatine supplementation is ceased:</p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/15263100" target="_blank">Study Link &#45; Effect of ceasing creatine supplementation while maintaining resistance training in older men.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> Strength (1&#45;repetition maximum [1&#45;RM]), endurance (maximum number of repetitions over 3 sets at 70&#45;80% 1&#45;RM), and [lean tissue mass] (dual&#45;energy X&#45;ray absorptiometry) were assessed before and after 12 weeks of [creatine] cessation combined with reduced&#45;volume training. No changes in strength or [lean tissue mass] occurred. </blockquote></em></p>
<p> Anyone who even implies that creatine &ldquo;just causes the cells to hold more water&rdquo; simply looks foolish in the eyes of those who have studied the existing research. </p>
<p> It&#39;s possible, too, that, far from being an unwanted side&#45;effect, creatine&#39;s effect on cellular hydration may be one of the factors <strong><em>responsible</em></strong> for the growth&#45;promoting actions of creatine. It&#39;s important to remember that a hydrated cell is integral for the process of growth, repair, and recovery to take place optimally. </p>
<p> It&#39;s important to note as well that the <strong><em>real</em></strong> benefits of creatine occur in the <strong><em>long&#45;term</em></strong>, not the short&#45;term. As creatine allows a person to consistently train with greater power and intensity, creatine can be a major factor in fostering long&#45;term gains in muscle size and function. The long&#45;term gain in muscle mass experienced while taking creatine will manifest as <strong><em>actual muscle tissue</em></strong> &#45; <strong><em>not</em></strong> simply water&#45;weight. </p>
<p> As evidence, several lines of research indicate that creatine monohydrate supplementation is able to trigger the activation of satellite cells (satellite cell activation is considered to be a primary event in the growth and regeneration of muscle tissue):</p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/10683092" target="_blank">Study Link &#45; Dietary creatine monohydrate supplementation increases satellite cell mitotic activity during compensatory hypertrophy.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> [C]reatine supplementation in combination with an increased functional load results in increased satellite cell mitotic activity.</blockquote></em></p>
<p><a href=""http://www.acsm-msse.org/pt/re/msse/abstract.00005768-200305000-00009.htm;jsessionid=Jx3Qt2VzcDP2QNL4N57XpM3bc1KyV9ymVbyQqTnDHFYVPxnnrTpW!-32953442!181195629!8091!-1 target="_blank"> Study Link &#45; The Effects of Ergogenic Compounds on Myogenic Satellite Cells.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> Creatine in the monohydrate form induced differentiation of myogenic satellite cells...These results provide initial evidence for a mechanistic understanding of observed effects in vivo of increased muscular size and strength from creatine supplementation.</blockquote></em></p>
<p> In a practical sense, if a person finds that the athletic gains they noticed from taking creatine disappear soon after creatine supplementation is stopped, it&#39;s usually an implicit admission that either they didn&#39;t take it for long enough to notice the longer&#45;term gains, or their training and/or diet are insufficient to support meaningful gains in the first place. Rather than blaming creatine, such people would be well&#45;served to shore up their diet and training regimens in order to then reap the full athletic and muscle&#45;building benefits of creatine.</p>

<h2>Q. It has been said that some new types of creatine don&#39;t cause bloating. Is this true?</h2>
          <p><font color="be1622"><strong> A. </strong></font>Many &ldquo;new&rdquo; types of creatine (creatine ethyl ester, buffered creatines, liquid creatines, and several others) are being marketed as if they somehow lack the cell volumizing ability of creatine monohydrate (of course, in marketing lingo, we&#39;re told that these creatines don&#39;t cause &ldquo;bloating&rdquo; &#45; a term with clearly negative connotations which is probably used purposefully to mislead the consumer). </p>
<p> There are several factors to consider: </p>
<p> First off, even <strong><em>assuming</em></strong> these new creatines are viable forms of creatine at all (which is <strong><em>not</em></strong> the case for many of them, as we shall see), on a cellular level, there&#39;s no reason to believe that some types of creatine would work differently than others. Again, no matter what molecule creatine is attached to when you consume it, creatine will be stored in the cells as phosphocreatine (as the body attaches a phosphate to creatine intracellularly). There&#39;s simply no reason to believe that some types of creatine will &ldquo;magically&rdquo; work differently once creatine is taken up by the cell. </p>
<p> Empirically though, some people do report less bloating when taking types of creatine other than creatine monohydrate. But this doesn&#39;t mean that these products are, in any way, <strong><em>better</em></strong> than creatine monohydrate. </p>
<p> The reason is that these product often contain <strong><em>very little creatine</em></strong> &#45; thus, logically, the user won&#39;t experience the cellular hydration associated with creatine. Of course, such products often contain various stimulants such as caffeine, so a performance enhancing effect is often noticeable, but these effects are <strong><em>not </em></strong>due to creatine. A few years back, a certain popular brand of liquid creatine, which claimed to offer benefits above and beyond creatine monohydrate, was independently tested, and was found to contain almost no creatine whatsoever.</p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/15513279?ordinalpos=1&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_DefaultReportPanel.Pubmed_RVDocSum" target="_blank">Study Link &#45; The creatine content of Creatine Serum and the change in the plasma concentration with ingestion of a single dose.</a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> Analysis showed 5 ml of Creatine Serum to contain &lt;10 mg [creatine monohydrate] and approximately 90 mg creatinine. Phosphorylcreatine was not detectable and only a trace amount of phosphorous was present. Total nitrogen analysis ruled out significant amounts of other. forms of creatine. We conclude that the trace amounts of creatine in the product would be too little to affect the muscle content even with multiple dosing.</blockquote></em></p>
<p> Other types of creatine (such as esters and chelates) may offer some slight benefits, but often, the stability and efficacy of these products is questionable as well. It&#39;s highly unlikely that these products offer any benefits <strong><em>over</em></strong> creatine monohydrate, but people may notice less water retention simply because they are consuming significantly <strong><em>lower doses</em></strong> of creatine when they take esters and chelates (the recommended dose of these products contains far less actual creatine than the recommended dose of many creatine monohydrate products). </p>
<p> When we compare apples to apples, the same reduction in water&#45;weight gain could be achieved using similarly low doses of creatine monohydrate (which may be all that is necessary to reap creatine&#39;s benefits as an athletic or anti&#45;aging substance in the first place). So, low doses of creatine <strong><em>from any source</em></strong> are unlikely to cause noticeable water&#45;weight gain. It&#39;s usually only relatively high doses of creatine which have a visibly noticeable effect on cellular hydration. </p>
<p> But, it shouldn&#39;t be forgotten that creatine monohydrate is the <strong><em>only</em></strong> type of creatine which has been shown in countless studies to be stable, safe, and effective. In fact, preliminary research on some of the newfangled types of creatine currently being marketed indicates that they are likely to be quite <strong><em>unstable</em></strong> under physiologic conditions. <strong><em>If such products don&#39;t cause cellular hydration in the same way as creatine monohydrate, this is likely to be because these compounds degrade into useless creatine metabolites upon ingestion. As such, these products offer not a benefit, but an added risk when compared to creatine monohydrate.</em></strong></p>
<p> Along the same lines, when the word &ldquo;bloating&rdquo; is used, the term may be referring to the stomach upset some people notice when taking <strong><em>large</em></strong> doses of creatine monohydrate. But, this effect too is simply a function of <strong><em>dose</em></strong> and not of creatine monohydrate per se. Stomach upset, if it occurs when taking creatine monohydrate, can be easily rectified by lowering the dose taken.</p>

<h2>Q. Speaking of creatine dosage, is taking a loading dose of creatine necessary?</h2>
 <p><font color="be1622"><strong>A.</strong></font> Probably not. Many studies using creatine monohydrate have employed a loading dose of creatine (where creatine is initially taken in high doses to saturate the muscle cells) of approximately 20 grams per day for 5 days. The loading dose is often followed by a maintenance dose of 3 to 5 grams per day thereafter. </p>
 <p> But, although there is evidence to suggest that a loading dose is beneficial for quickly saturating muscles with creatine, other studies suggest that smaller doses of creatine, taken consistently, are able to saturate the muscle cells with creatine equally (though, logically, reaching muscle saturation will take longer). </p>
 <p> One of the most often&#45;cited studies in this regard, showed that muscle creatine concentrations were increased by 20% when 20 grams of creatine was taken over a six&#45;day period &#45; yet a similar increase was found when 3 grams of creatine was taken over a 28&#45;day period.</p>
 <p> <a href="http://jap.physiology.org/cgi/content/abstract/81/1/232" target="_blank">Study Link &#45; Muscle creatine loading in men.</a> </p>
 <p> Quote from the above study:</p>
 <blockquote><p><em> Muscle total creatine concentration increased by approximately 20% after 6 days of creatine supplementation at a rate of 20 g/day&hellip; A similar, but more gradual, 20% increase in muscle total creatine concentration was observed over a period of 28 days when supplementation was undertaken at a rate of 3 g/day&hellip; The ingestion of 3 g creatine/day is in the long term likely to be as effective at raising tissue levels as this higher dose. </blockquote></em></p>
 <p> So, it seems that creatine loading is <strong><em>not</em></strong> entirely necessary to reap benefits from creatine supplementation. </p>
 <p> But the question then arises: are there performance benefits to be gained from loading creatine which wouldn&#39;t be gained by taking maintenance doses on a regular basis? Some researchers suspect there may be. It&#39;s possible that a dramatic rise in muscle creatine stores may, in and of itself, trigger growth&#45;promoting mechanisms in the muscle cell. If this is true, we <strong><em>may</em></strong> want to devise strategies to load creatine as safely and efficiently as possible. </p>
 <p> As nearly every creatine user can attest, creatine isn&#39;t the most soluble of compounds when mixed in water. The advent of micronized creatine (creatine with a very small particle size) several years ago helped creatine <strong><em>suspend</em></strong> in water more efficiently (which serves to reduce creatine&#39;s gritty texture considerably), but particle size doesn&#39;t significantly affect a compounds solubility, and the relatively low solubility of creatine monohydrate can be problematic when large doses are taken. </p>
 <p> In general, 5 grams of creatine will require somewhere in the neighborhood of 16 ounces of water to be dissolved. And, of course, the more creatine is dissolved in liquid, the more can be absorbed into the bloodstream. If creatine is taken without sufficient liquids, its relatively poor solubility may draw water into the gastrointestinal tract, causing stomach upset or diarrhea. </p>
 <p> Also, when large doses of creatine are taken, the breakdown products of creatine which are formed may be able to provide a nitrogen (protein) source for various intestinal bacteria. Much of the gas and intestinal upset associated with creatine use may be attributable to the metabolism of creatine&#45;related compounds by intestinal bacteria. </p>
 <p> A certain researcher in the nutritional supplement field has written that the creatine metabolite creatin<strong><em>in</em></strong>e may be of benefit to intestinal health. This researcher has apparently confused the effects of beneficial intestinal bacteria with those of <strong><em>pathogenic</em></strong> intestinal bacteria. The existing research makes it very clear that intestinal bacteria is likely to produce <strong><em>toxic</em></strong> metabolites from creatinine. These metabolites are probably of relatively little significance in healthy individuals, but the formation of nitrogen&#45;based toxins by intestinal bacteria could is certainly <strong><em>not</em></strong> beneficial, and could easily account for much of the stomach upset some creatine users notice. This is yet another reason why finding the right dose is so important with creatine. </p>
 <p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/5020825?dopt=Abstract" target="_blank">Study Link &#45; Implication of creatinine and gut flora in the uremic syndrome: induction of &quot;creatininase&quot; in colon contents of the rat by dietary creatinine.</a> </p>
 <p> Quote from the above study: </p>
 <blockquote><p><em> &hellip;microbial action could lead to the formation of toxic products from creatinine that, in the presence of decreased renal function, would be retained. </blockquote></em></p>
 <p> And the fact is that many people unknowingly consume much larger amounts of creatine than their body can efficiently absorb at any one time &#45; creating a surefire formula for stomach upset. </p>
 <p> Most people taking creatine may even be taking far higher amounts than they <strong><em>think</em></strong> they are. For example, the standard serving size of creatine listed on most straight&#45;creatine monohydrate products is 5 grams &#45; a reasonable dose by most standards. But, this serving size is often listed rather nebulously as a &ldquo;heaping teaspoon.&rdquo; Of course, in actual practice, few people measure their creatine dose precisely, and a heaping teaspoon of creatine usually ends up being six, seven, or eight grams of creatine (depending upon how generously we interpret the term &ldquo;heaping,&rdquo; and whether an actual measuring teaspoon is used). And let us not forget that most bodybuilders aren&#39;t known for their sense of precision or moderation when it comes to substances which can improve performance. </p>
 <p> So a &ldquo;heaping teaspoon&rdquo; of creatine taken 4 times a day could <strong><em>easily</em></strong> amount to 28&#45;32 grams of creatine at the very least &#45; a pretty far cry from the 20 grams we&#39;d be shooting for in most creatine&#45;loading protocols. </p>
 <p> The take home message is that it <strong><em>may</em></strong> be worthwhile to give creatine loading a try, assuming proper doses are taken, spaced out over the course of the day, and taken with sufficient water for best absorption. Excessive doses of creatine (especially large doses taken all at once) are quite likely to cause stomach upset, and this can give users a bad first impression of creatine. But it&#39;s very important to remember, again, that, it&#39;s the <strong><em>dose</em></strong> of creatine responsible for this effect, not creatine per se. </p>




<h2>Q. Some sellers of nutritional supplements claim that creatine monohydrate is unstable and converts into the toxic compound, creatin<em>in</em>e, rapidly when mixed with liquids. They also claim that creatine monohydrate degrades to creatinine rapidly when exposed to the acidic environment of the stomach, and that buffered versions of creatine are the most stable, effective forms. Are these claims true?</h2>
<p><font color="be1622"><strong> A. </strong></font> In a word: No. Not only has buffered creatine <strong><em>not</em></strong> been shown to be, in any way, superior to creatine monohydrate, but the very premise upon which buffered creatine is promoted &#45; that creatine monohydrate degrades rapidly into creatinine &#45; is faulty. Anybody who has actually followed the research on creatine monohydrate will realize immediately that the scientific&#45;sounding claims made by the sellers of buffered creatine amount to little more than scare tactics and propaganda concocted in order to sell their product. The reality is that the conversion of creatine monohydrate to creatinine is almost a complete non&#45;issue for all practical purposes. </p>
<p> But, at the very least, the exaggerated claims of the sellers of buffered creatines give us the opportunity to learn the truth about creatinine &#45; a natural byproduct of creatine metabolism within our bodies. </p>
<p> Within the muscle cell, approximately 60 &#45; 70% of total creatine is stored as phosphocreatine &#45; the substance which donates a phosphate and regenerates the energy molecule, ATP. Both creatine and phosphocreatine are polar, electrically charged molecules which don&#39;t freely pass out of the cell. We know that creatine can enter the cell, of course, but the hard time it has getting <strong><em>out</em></strong> of the cell once phosphocreatine is formed is why creatine supplementation is able to cause such dramatic increases in muscle creatine and phosphocreatine concentrations. </p>
<p> Within the cell, a <strong><em>small</em></strong> percentage of creatine and phosphocreatine are converted into the electrically inert substance, creatinine. Because creatinine lacks the polar nature and electrical charge of its predecessors, it is able to freely exit the cell, and is subsequently excreted by the kidneys. This slow and steady conversion of creatine and phosphocreatine to creatinine is why muscle creatine levels take several weeks to return to pre&#45;supplementation level when creatine supplementation is ceased. </p>
<p> Now, the makers of buffered creatine don&#39;t deny that creatinine is a natural byproduct of creatine metabolism. But they <strong><em>do</em></strong> make the explicit claim that much if not all of the creatine from creatine monohydrate supplements converts to creatinine when mixed with liquids, or in the acidic environment of the gastrointestinal tract. They also go on to claim that the side effects associated with creatine are due to the formation of creatinine <strong><em>before</em></strong> creatine even reaches the muscle. </p>
<p> But these claims are utter nonsense, as can be easily demonstrated by a look at the extensive scientific literature on the subject. </p>
<p> First of all, it&#39;s been shown by many researchers that the conversion of creatine into creatinine in solution actually occurs relatively <strong><em>slowly</em></strong> &#45; not in seconds or minutes, but rather, in hours or even days. To give a frame of reference, creatine conversion to creatinine after a <strong><em>full day</em></strong> in aqueous solution (mixed with water) at room temperature has been shown to occur at a rate of around 1&#45; 2% <strong><em>at the most</em></strong> &#45; a far cry from the 100% conversion in minutes or seconds as <strong><em>explicitly</em></strong> stated by the sellers of buffered creatine. </p>
<p> As evidence, researchers attempting to create creatine&#45;fortified food products have extensively studied the stability of creatine over a wide range of pH values and storage temperatures. Their research <strong><em>clearly</em></strong> indicates that the conversion of creatine to creatinine is likely to be a <strong><em>complete</em></strong> non&#45;issue for all practical usages of creatine monohydrate powder. </p>
<p> For example, patent research for creatine&#45;fortified foods conducted by a respected group of creatine researchers found the following: </p>
<p> <strong> &bull; Creatine in aqueous solution is <em>completely</em> stable for 8 hours at 25 &deg; C (77 &deg; F) at a pH of 7.5 (room&#45;temperature water). </strong></p>
<p> <strong> &bull; Creatinine formation from creatine after <em>3 days</em> at pH 5.5, 4.5, and 3.5 was 4%, 12%, and 21% respectively. </strong></p>
<p align="center" class="style5"><img src="http://www.integratedsupplements.com/email/images/CreatineGraph.jpg" width="490" height="458" border="0" alt="">
<p> This data is from: </p>
<p> <a href="http://patft.uspto.gov/netacgi/nphParser?Sect1=PTO1&Sect2=HITOFF&d=PALL&p=1&u=%2Fnetahtml%2FPTO%2Fsrchnum.htm&r=1&f=G&l=50&s1=5968544.PN.&OS=PN/5968544&RS=PN/5968544" target="_blank">Patent Link &#45; Compositions containing creatine.</a></p>
<p> See also: Harris, R C (2001) Effects and safety of dietary and supplementary creatine. In: Creatine. From basic science to clinical application. Paoletti R, Poli A and Jackson A S (eds) Kluwer Academic Publishers, Dordrecht, Netherlands. pp 33&#45;39. </p>
<p> And, in addition to this research, the work of other researchers confirms the remarkable stability of creatine monohydrate: </p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/12093528?ordinalpos=&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.SmartSearch&log$=citationsensor" target="_blank">Study Link &#45; A simple LC method with UV detection for the analysis of creatine and creatinine and its application to several creatine formulations. </a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> The first&#45;order degradation constant for creatine [was] calculated from the slope of the line and was 0.0263 per day at 25</em> &deg; <em> C. </blockquote></em></p>
<p> So, by all scientific accounts, it&#39;s clear that the conversion of creatine to creatinine simply <strong><em>doesn&#39;t</em></strong> take place in solution very quickly at all (even in acidic mediums like citrus juices or stomach acid). </p>

<h2> Q. So creatine, for all practical purposes, doesn&#39;t convert to creatinine when we prepare our creatine mixtures, but what about the claim that creatine converts to creatinine before it reaches our muscles? Does &ldquo;un&#45;buffered&rdquo; creatine convert to creatinine <em>inside</em> our body to any meaningful extent?</h2>
 <p><font color="be1622"><strong> A. </strong></font> No, not to any meaningful extent. </p>
<p> In the above graph, we see that creatine remained reasonably stable for at least four hours in a solution with a pH of 3.5. After taking a dose of creatine, serum levels of creatine reach their peak 2&#45;3 hours after ingestion (depending upon the dose taken). So, even stomach acid is unlikely to cause creatinine formation to any significant extent. </p>
<p> And more directly, various studies have looked at the <em>pharmacokinetics</em> of creatine (pharmacokinetics is, basically, the study of how ingested compounds &ldquo;move&rdquo; around the body, what they&#39;re converted into, and how they&#39;re excreted). These studies simply show <strong><em>no evidence</em></strong> that creatine is massively degraded into creatinine before it reaches our muscles &#45; quite the contrary, in fact. </p>
<p> The following study looked at serum creatine and serum creatinine levels in subjects who consumed a single 20 gram dose of creatine. Creatine and creatinine levels were measured over a six hour time&#45;period. </p>
<p> While the researchers found that serum creatine levels increased greatly (50&#45;fold, or 5000% at peak levels), serum creatinine increased by only a modest, biologically insignificant amount (13% at peak levels). </p>
<p> <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T99-3Y168Y6-4&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=b1d41a1ccab0f9d75059ac7ab9fb9d30" target="_blank">Study Link &#45; Acute creatine ingestion in human: Consequences on serum creatine and creatinine concentrations. </a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> These results suggest that when acute doses of [creatine] are ingested in humans, the degree of conversion of exogenous [creatine] to [creatinine] in the stomach and the gut can be considered as negligible following the first 6 h of ingestion. </blockquote></em></p>
<p> So, even a large dose of creatine (20 grams) <strong><em>did not</em></strong> lead to a meaningful increase in serum creatinine levels. Considering the fact that creatine reaches peak levels in serum after 2&#45;3 hours, and returns to baseline levels after approximately 6 hours <strong><em>without</em></strong> any appreciable increase in serum creatinine, it&#39;s simply unfounded to say that creatine converts to creatinine before it reaches our muscles. </p>
<p> Some studies show that creatine supplementation can lead to slight elevations in urinary creatinine concentrations, but many studies show creatine supplementation to have no such effect. In the following study, when subjects consumed creatine monohydrate in doses of 20 grams per day for five days followed by a dose of 5 grams per day for five days, researchers reported that this creatine intake had <strong><em>no effect </em></strong>on urinary creatinine levels. </p>
<p> <a href="http://www.clinchem.org/cgi/content/full/46/2/295" target="_blank">Study Link &#45; Effect of oral creatine supplementation on random urine creatinine, pH, and specific gravity measurements. </a></p>
<p> Quote from the above study: </p>
<blockquote><p><em> This short&#45;term study investigated the effects of oral creatine supplementation on urinary creatinine, pH, and specific gravity values. Individual plots of all discrete urine specimen values did not reveal any apparent effect of creatine administration on these measurements. </blockquote></em></p>
<p><em> Note: Exercise itself has been shown to increase creatinine excretion, and many creatine studies involve intense exercise. It&#39;s possible that some of the increases in creatinine excretion seen in the published literature may have more to do with the effects of exercise rather than creatine consumption. </em></p>
<p> Studies consistently show that the <strong><em>vast</em></strong> majority of excess creatine consumed is excreted unchanged as creatine &#45; not creatinine. As evidence, the following study supplied a loading dose of creatine monohydrate (20 grams per day for 5 days) to an individual, followed by a 30&#45;day washout period, followed by another loading period. </p>
<p> The researchers found that once tissue creatine stores were full, the excess creatine consumed was excreted as creatine &#45; while creatinine level remained within normal limits: </p>
<p> <a href="http://www.pharmacy.unc.edu/pkpd/AMP%20Articles/Rawson%20et%20al%20JSCR%202004%20Case%20Study.pdf" target="_blank">Study Link &#45; Effects of Repeated Creatine Supplementation on Muscle, Plasma, and Urine Creatine Levels.</a> </p>
<p> Quote from the above study: </p>
<blockquote><p><em> Urine creatine increased profoundly during both bouts of supplementation, with no obvious differences between supplementation bouts. Creatine retained by the body (total creatine ingested minus total creatine recovered in the urine) was 36.8 g during bout 1 and 36.6 g during bout 2. The man excreted 63.2% and 63.4% of supplemented creatine during bouts 1 and 2, respectively. Urine creatinine values were within normal limits during both bouts 1 and 2 of supplementation on all but one testing day, and day&#45;to&#45;day fluctuations were typical of a healthy, nonvegetarian adult. </blockquote></em></p>
<p> These studies, taken together, are <strong><em>clear</em></strong> evidence that creatine does <strong><em>not</em></strong> convert to creatinine in any meaningful amount <strong><em>before</em></strong> we consume it; and also that creatine does <strong><em>not</em></strong> convert to creatinine in any meaningful amount <strong><em>after</em></strong> we consume it &#45; either before, it reaches our muscles, or when an excess is being excreted in the urine. The simple fact is that the overwhelming amount of creatine research as a whole <strong><em>directly</em></strong> refutes the <strong><em>explicit</em></strong> claims of those selling buffered creatine. </p>
<p> And, in strictly logical sense, if creatine monohydrate <strong><em>did</em></strong> convert to creatinine at the rates the buffered creatine&#45;sellers state, taking creatine wouldn&#39;t elevate muscle creatine or phosphocreatine stores, improve performance, or aid in muscle building at all &#45; yet it <strong><em>clearly</em></strong> does all of these things quite well. </p>
<p> So, in essence, the sellers of buffered creatine have set up a biological straw man. They&#39;ve posited their product as a solution to a phenomenon &#45; creatine to creatinine conversion &#45; which the scientific literature indicates simply doesn&#39;t exist in any practical, meaningful sense. </p>
<p> The only time the creatine to creatinine conversion achieves practical significance is when trying to stabilize creatine in liquids for <strong><em>long</em></strong> periods of time. This is why so many liquid creatine products have continually failed to deliver the benefits of powdered creatine monohydrate. These products may be <strong><em>many months</em></strong> old by the time they&#39;re consumed, and in these products, the conversion of creatine to creatinine <strong><em>has</em></strong> proven to be a serious problem. As we referenced above, when independently tested, certain liquid creatine products have been found to contain almost no creatine whatsoever, while containing relatively high amounts of creatinine. </p>




<h2>Q. Why do some people notice fewer side effects with buffered creatine (or esters, or chelates) than with creatine monohydrate?</h2>
<p><font color="be1622"><strong> A. </strong></font> As noted above, most, if not all, creatine monohydrate&#45;related side effects can be rectified simply by consuming <strong><em>less creatine</em></strong> &#45; or smaller doses of creatine spaced out over the course of the day. If we do this, possible side&#45;effects like stomach upset and water&#45;retention will be largely eliminated. </p>
<p> Now of course, when we compare apples to apples, we see that the recommended dose of buffered creatine (and similarly, creatine esters and chelates <em>et al</em>.) will supply the body with just that &#45; <strong><em>low doses of creatine.</em></strong></p>
<p> On a molecular level, creatine monohydrate, which is simply creatine bound to a water molecule, will contain approximately 88% creatine by weight. Buffered creatine is simply creatine monohydrate with alkaline substances added to it &#45; so, logically, it will contain less creatine than an equal weight of pure creatine monohydrate. Many other types of creatine salts, esters, and chelates will also contain far less creatine by weight relative to creatine monohydrate. For instance, creatine&#45;magnesium chelate, will contain 45% creatine &#45; roughly half that of creatine monohydrate. </p>
<p> So, the reason people sometimes notice fewer side&#45;effects with the &ldquo;newer&rdquo; creatine products is simply because, in one way or another, they&#39;re consuming <strong><em>less creatine</em></strong> &#45; plain and simple. It isn&#39;t because one creatine is &ldquo;buffered,&rdquo; or more soluble, or &ldquo;stronger,&rdquo; or more bioavailable, or absorbed better, or anything like that &#45; although this is exactly what the marketing behind these products would have us believe. </p>
<p> And speaking of the side effects associated with creatine monohydrate, it&#39;s worth noting, too, that some low&#45;cost creatine monohydrate powders may cause gastrointestinal side effects if they are not <strong><em>pure</em></strong> creatine. In years past, more than a few sources of creatine monohydrate were found to contain fairly significant levels of creatinine and other contaminants as the result of an inefficient production process. It&#39;s conceivable that cheaply produced creatine products may cause side effects because they are not, in fact, pure creatine monohydrate. </p>
<p> The lesson is: those who have experienced side effects with creatine monohydrate need not resort to over&#45;priced and untested alternatives &#45; they should merely make an effort to seek out creatine monohydrate of the highest purity, and find a dose that&#39;s right for them. The long&#45;term health benefits which are likely to result from creatine consumption are sure to make such simple experimentation more than worthwhile in the long&#45;run. </p>

<h2>Q. What about creatine esters like creatine ethyl ester?</h2>
<p><font color="be1622"><strong> A. </strong> </font>The rampant promotion of creatine esters in recent years is yet another example of how greed and scientific speculation have served to tarnish the reputation of the entire sports nutrition industry. In the nearly <strong><em>complete absence</em></strong> of efficacy and safety research, creatine esters have been introduced into the nutritional supplement marketplace on the mere <strong><em>assumption</em></strong> that they would act as highly soluble, and highly absorbable forms of creatine. </p>
<p> But what limited research exists on these compounds indicates that this is <strong><em>not</em></strong> the case. With creatine esters, we simply find that, yet again, the claims of many supplement marketers are <strong><em>completely</em></strong> unsubstantiated. Unfortunately, if the history of the sports supplement industry is any indication, some customers will keep falling for the creatine&#45;ester hype, the baseless claims will be repeated <em>ad nauseam</em>, and the products will continue to be sold, even after their worthlessness has become well&#45;documented. </p>
<p> It&#39;s actually hard to keep up with all of the outrageous claims which are made for creatine esters, but there are a few proposed mechanisms (ranging from the highly unlikely, to the scientifically impossible) by which creatine ethyl esters are often claimed to provide benefits above and beyond creatine monohydrate. But as the research stands now, the outlook is simply not good for creatine ethyl ester as a viable source of supplemental creatine. </p>
<p> As a bit of background, creatine esters are forms of creatine with an alcohol attached (at the caboxylic group of the molecule) whereas creatine monohydrate contains a water molecule attached at this same functional group. The most common creatine ester, creatine ethyl ester (CEE), is creatine bound to the alcohol, ethanol (more specifically, the ingredient commonly used in supplements is known as creatine ethyl ester hydrochloride). This compound will have a greater solubility in water than creatine monohydrate, and the presence of the lipophilic (fat&#45;loving) esters on the creatine molecule is said by many to (somehow) allow greater creatine uptake by the cells. </p>
<p> But, let&#39;s take a closer look at a few of the more common claims made for creatine esters: </p>
<p> <font color="be1622"><strong> Faulty Claim #1 </strong></font> &#45; Creatine Ethyl Ester is more fat&#45;soluble than creatine monohydrate, and will therefore cross (fat&#45;containing) cell membranes, and enter cells more efficiently. This could lead to greater creatine concentrations within the cell. </p>
<p> <font color="be1622"><strong> The Truth: </strong></font> This claim is without any substantiation, and doesn&#39;t even make sense from a <strong><em>theoretical</em></strong> standpoint. The presence of esterase enzymes in intestinal cells and the blood will break down CEE into creatine and ethanol quite rapidly. By the time CEE reaches the muscle cell, the vast majority of ester will already be dissociated from the molecule, and what&#39;s left (if we&#39;re lucky) will be plain old creatine. There&#39;s simply no reason to believe that a substantial amount of CEE will remain intact by the time it reaches the target cell. Similarly, there&#39;s no legitimate reason to believe that CEE will bypass creatine transporters, or be able to &ldquo;force&rdquo; the cell to hold more creatine or phosphocreatine. </p>
<p> In fairness, the researchers who are the patent&#45;holders of creatine esters never anticipated that creatine esters would enter the target cell intact. The above nonsensical claim seems to have derived exclusively from the clueless marketers of creatine ethyl esters, and some ill&#45;informed authors within the nutritional supplement industry. </p>
<p> The patent holders of creatine esters assumed that the ester forms would simply deliver more creatine into the bloodstream than creatine monohydrate. Although this doesn&#39;t appear to be true in any practical sense either, this hypothesis is certainly more reasonable than assuming that the esters will be absorbed intact by the muscle cells. </p>
<p> We can see, in the following quote from the patent holders of creatine esters, that their proposed mechanism of action involved the possibility that creatine esters would simply be absorbed from the gastrointestinal tract more efficiently than creatine monohydrate: </p>
<p> <a href="http://www.google.com/patents?hl=en&lr=&vid=USPATAPP10363761&id=tkKJAAAAEBAJ&oi=fnd&dq=creatine+esters" target="_blank">Patent Link &#45; Creatine ester pronutrient compounds and formulations. </a></p>
<p> Quote from the above patent: </p>
<blockquote><p> <em> An additional advantage of creatine esters is that, as the creatine ester compound moves from the intestinal tissue into the bloodstream, the creatine ester compounds themselves are biologically inactive, but esterase enzymes present in both the intestinal cells and the blood break the ester bonds of creatine ester, converting it to biologically active creatine. In other words, the advantages of the creatine ester are preserved during transport, such as increased solubility and permeability, but when needed, the creatine is available to be converted into its biologically active form. </blockquote></em></p>
<p> It&#39;s worth noting that if a small amount of creatine esters <strong><em>are</em></strong> absorbed into the target cell intact, this could potentially be a <strong><em>very</em></strong> bad thing. We simply have no evidence that these esters can safely increase phosphocreatine levels the way creatine monohydrate can. It&#39;s entirely possible, that if these esters enter the target cell intact, they may actually <strong><em>inhibit</em></strong> phosphocreatine synthesis by interfering with the enzyme, creatine kinase (remember, CEE, in its intact form is completely foreign to human metabolism. Unlike free creatine there&#39;s a chance that such a foreign molecule will <strong><em>inhibit</em></strong> the enzyme systems designed to utilize creatine). As a frame of reference, inhibitors of creatine kinase include known neurotoxins such as ethylene oxide and acrylamide, which are implicated in degeneration of the nervous system. </p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/8472675?ordinalpos=1&itool=EntrezSystem2.PEntrez.Pubmed.Pubmed_ResultsPanel.Pubmed_DiscoveryPanel.Pubmed_Discovery_RA&linkpos=3&log$=relatedarticles&logdbfrom=pubmed" target="_blank">Study Link &#45; Effects of neurotoxins on brain creatine kinase activity. </a></p>
<p> Quote from the above study: </p>
<blockquote><p> <em> The inhibition of [creatine kinase] may play a role in the pathogenesis of distal axonal degeneration in the central and peripheral nervous systems. </blockquote></em></p>
<p> It&#39;s unknown if this fact will have any practical significance as related to the consumption of creatine ethyl ester, (as the position of the ethyl ester indicates that it <strong><em>may</em></strong> not directly interfere with creatine binding to creatine kinase) but it&#39;s certainly not a stretch to say that creatine ethyl esters could have negative effects on these same enzyme systems by indirect means (ethanol itself inhibits many enzyme systems even without being bound to creatine). The point is that scientific investigation into these possibilities is simply non&#45;existent. Those consuming creatine esters should be aware that they are doing so in the <strong><em>complete absence</em></strong> of long&#45;term safety data on the compound. As it stands now, creatine ethyl esters seem to offer all risk and no benefit. </p>
<p> <font color="be1622"><strong> Faulty Claim #2 </strong></font> &#45; Creatine monohydrate is poorly absorbed and inefficient. Large doses of creatine monohydrate are needed in order to saturate the tissues, and these doses can cause bloating. </p>
<p> <font color="be1622"><strong> The Truth: </strong></font> Those who say that creatine monohydrate is poorly absorbed are engaging in some <strong><em>very</em></strong> sloppy thinking, to say the least. Scores of existing research make it clear that creatine monohydrate is <strong><em>very</em></strong> well&#45;absorbed &#45; both from the gastrointestinal tract into the bloodstream, and from the bloodstream into the target cells. </p>
<p> As evidence of efficient gastrointestinal absorption, studies have repeatedly shown that excess creatine is almost completely excreted in the urine (if an ingested compound ends up in the urine, it means, by definition, that it has been absorbed from the gastrointestinal tract &#45; substances which are unabsorbed will be excreted in feces, and this just doesn&#39;t happen with creatine consumption): </p>
<p> <a href="http://jn.nutrition.org/cgi/content/abstract/105/4/428" target="_blank">Study Link &#45; Creatine Metabolism in Men: Urinary Creatine and Creatinine Excretions with Creatine Feeding.</a> </p>
<p> Quote from the above study: </p>
<blockquote><p> <em> There was no significant increase in fecal nitrogen during the creatine&#45;feeding period. Other investigators have reported the lack of significant amounts of isotope in the feces or other urine compounds after oral administration of [15N]creatine indicating that normally, urine is the only major excretory route of creatine and creatinine. </blockquote></em></p>
<p> What people misconstrue as evidence of creatine monohydrate&#39;s &ldquo;poor absorption,&rdquo; is that large doses of creatine monohydrate can draw water into the gastrointestinal tract if not consumed with sufficient liquid. Therefore, large doses of creatine can potentially cause stomach upset. This simply means that creatine should always be consumed with sufficient liquid (approximately 16 oz of water for every 5 grams of creatine). But, equally as important, as we saw in the previous Integrated Supplements Newsletter, large doses of creatine simply aren&#39;t necessary in order to reap the full benefits of creatine. </p>
<p> As far as creatine absorption by the muscle (or other target) cell goes, we find, as well, that creatine, taken in the form of creatine monohydrate is <strong><em>very</em></strong> well absorbed. In fact, numerous studies have shown that creatine monohydrate is consistently able to elevate phosphocreatine stores <strong><em>to their maximal level</em></strong>. This point is an important one to consider &#45; no matter what type of creatine is taken, there is simply a <strong><em>finite</em></strong> limit to the amount of creatine and phosphocreatine a cell will hold. </p>
<p> If excess creatine is excreted, this <strong><em>doesn&#39;t</em></strong> mean that creatine is poorly absorbed by the cell, <strong><em>but that the cells have already been saturated with creatine</em></strong>. If creatine monohydrate were poorly (or inefficiently) absorbed by the target cell, we would see excretion rates remain constant throughout the supplementation period &#45; but we don&#39;t see this at all. What we do see is creatine excretion rates increasing as the cells become fully saturated with the maximum level of creatine they can hold: </p>
<p> <a href="http://www.ncbi.nlm.nih.gov/pubmed/1327657?dopt=Abstract" target="_blank">Study Link &#45; Elevation of creatine in resting and exercised muscle of normal subjects by creatine supplementation.</a> </p>
<p> Quote from the above study: </p>
<blockquote><p> <em> Uptake into muscle was greatest during the first 2 days of supplementation accounting for 32% of the dose administered in three subjects receiving 6 x 5g of creatine monohydrate/day. In these subjects renal excretion was 40, 61 and 68% of the creatine dose over the first 3 days. Approximately 20% or more of the creatine taken up was measured as phosphocreatine. </blockquote></em></p>
<p> Where creatine monohydrate has repeatedly been shown to increase muscle creatine stores to their <strong><em>maximum level</em></strong>, it&#39;s hard to fathom how anyone could say that creatine monohydrate is poorly absorbed &#45; especially considering that no other type of creatine has been shown to increase muscle creatine/phosphocreatine stores <strong><em>at all</em></strong>, never mind more efficiently than creatine monohydrate. </p>
<p> <font color="be1622"><strong> Faulty Claim #3 </strong></font> &#45; Creatine Ethyl Ester is more stable than creatine monohydrate, and will be absorbed and utilized more efficiently. </p>
<p> <font color="be1622"><strong> The Truth: </strong></font> Despite the many marketing claims which are made for creatine esters, this, in a nutshell, is the stated claim of the researchers who actually hold the patent on creatine esters. But, when discussing buffered creatines, we already showed that creatine monohydrate is, in fact, <strong><em>remarkably</em></strong> stable for all practical purposes &#45; it simply doesn&#39;t degrade into creatinine as the patent&#45;holding researchers assumed. </p>
<p> It&#39;s important to note that patents are <strong>not</strong> scientific studies. Patent applicants are free to speculate on how their inventions <strong>may</strong> be improvements upon existing inventions, but they are not required to prove this before patenting something. Often, the theories of patent holders (even if the patent holders happen to be scientists) turn out to be incorrect; and the invention offers no benefit over existing ones. For example, in the case of creatine esters, there are now several lines of evidence showing that creatine esters may very well convert to creatinine at an <strong><em>accelerated</em></strong> rate versus creatine monohydrate. </p>
<p> So, we may have a case of the pot calling the kettle black, so to speak. What little research is available on creatine esters seems to indicate strongly that <strong><em>they,</em></strong> and <strong><em>not </em></strong>creatine monohydrate, convert into creatinine <strong><em>very</em></strong> rapidly, both in solution, and in the body once consumed. </p>
<p> The first piece of evidence along these lines actually came from the creatine ethyl ester marketers themselves. </p>
<p> In the United States, companies seeking to introduce novel dietary ingredients into the food supply, or into the realm of dietary supplements are required to notify the Food and Drug Administration, and provide evidence that the substance is &ldquo;reasonably expected to be safe.&rdquo; </p>
<p> But the evidence submitted to the FDA supposedly supporting the safety of creatine ethyl ester was anything but convincing. First off, the vast majority of scientific references supplied by the marketers of CEE actually referenced the safety of <strong><em>creatine monohydrate, </em></strong>not creatine ethyl ester. </p>
<p> Noting that the submission for new dietary ingredient status suffered from a nearly <strong><em>complete</em></strong> lack of safety data on creatine ethyl ester <em>per se</em>, the FDA wrote in their reply: </p>
<blockquote><p><em> FDA has carefully evaluated the information in your submission and the agency has significant concerns about the evidence upon which you rely to support your conclusion that &ldquo;Creatine Ethyl Ester HCL&rdquo; when used under the conditions recommended or suggested in the labeling of your product, will reasonably be expected to be safe. </blockquote></em></p>
<p> In subsequent submissions to the FDA, the marketers of creatine ethyl ester argued that because creatine ethyl ester rapidly breaks down into creatine and ethanol, the safety of the compound could be logically deduced from the safety and widespread use of creatine (in monohydrate form) and ethanol (the alcohol found in alcoholic beverages). </p>
<p> But this strange sort of logic is riddled with flawed thinking. </p>
<p> We mentioned previously that if some creatine ethyl ester is absorbed intact by the target cell, the compound could be at least mildly toxic. This toxicity would be <strong><em>completely unique </em></strong>to creatine esters, and would be a complete non&#45;issue with creatine monohydrate which lacks the ester linkage of creatine ethyl ester. In light of the possibility for harm, more thorough testing of the <strong><em>actual compound</em></strong> being introduced into the marketplace doesn&#39;t seem like too much to ask for. </p>
<p> But beyond merely speculative differences between creatine monohydrate and creatine ethyl ester, there appear to be documented differences in how each compound is metabolized. The first piece of evidence for this is in the documents submitted to the FDA by the creatine ethyl ester marketers themselves. </p>
<p> In one of the studies submitted to the FDA by the marketers of CEE, radioactively labeled creatine ethyl ester was given to rats allowing the researchers to see exactly how the substance is metabolized. </p>
<p> But, although the marketers of creatine ethyl ester use the findings from this study as evidence to support their contention that creatine ethyl ester is metabolized similarly to creatine monohydrate, their own statements about the study show clearly that this is not the case. </p>
<p> To quote the CEE marketers in their submission to the FDA: </p>
<blockquote><p><em> &hellip;following oral administration the [4&#45; 14C] Creatine Ethyl Ester is rapidly absorbed from the gastro&#45;intestinal tract, with radioactivity being detected in plasma within three minutes following administration. The peak concentration of the associated form (ester) occurred at five minutes following administration, and accounted for less than 15% of the total radioactivity present in the plasma. </blockquote></em></p>
<p> So, we can see that, although the majority of creatine ethyl ester is broken down before it enters the bloodstream, 15% of it is absorbed intact. It&#39;s likely that most of this CEE is degraded in plasma, but as of now, we don&#39;t know how much, if any is taken up by the cells intact. The quote continues: </p>
<blockquote><p><em>This indicates that its dissociation into creatine and ethanol is rapid and nearly complete within this initial five&#45;minute period. At ten minutes following administration, approximately 2% of the total radioactivity present in plasma was in the associated ester form, with none detected after the ten&#45;minute time point. The rapid dissociation of the ethyl ester in the plasma was accompanied by a concurrent rapid increase in creatine and creatinine levels as suggested in the earlier study (see Attachment 24). The peak level of creatine in plasma was equivalent to about 12% of the total radiocarbon present, and occurred at approximately thirty minutes following administration. The concentration gradually declined, and gave rise to creatinine levels that increased to approximately 80&#45;90%, where they remained throughout the duration of this study period. This pharmacokinetic profile is expected, since creatinine is the known major metabolite of creatine. </blockquote></em></p>
<p> But we know from the previous studies in this newsletter that creatine monohydrate <strong><em>doesn&#39;t</em></strong> lead to a &ldquo;rapid increase in &hellip;creatinine levels&rdquo; as, apparently, creatine ethyl ester does. So, despite the contention of the CEE&#45;marketers, this &ldquo;pharmacokinetic profile&rdquo; is absolutely <strong><em>NOT</em></strong> to be expected from any compound which is said to be metabolized similarly to creatine monohydrate. </p>
<p> In fact, in this creatine ethyl ester study, 80&#45;90% of the radioactivity was measured as creatinine &#45; indicating that, quite unlike creatine monohydrate, the <strong><em>majority</em></strong> of creatine ethyl ester rapidly degrades into creatinine upon ingestion. </p>
<p> And subsequent studies have confirmed that indeed, that there are some <strong><em>major</em></strong> differences between the stability of creatine monohydrate and creatine ethyl ester. These other studies <strong><em>also</em></strong> show that creatine ethyl ester may be particularly prone to rapidly convert to creatinine upon ingestion. </p>
<p> A study presented at the 4th International Society of Sports Nutrition (ISSN) annual meeting in 2007 tested the stability of creatine monohydrate and creatine ethyl ester in acidic solutions (pH of 1). </p>
<p> The study found: </p>
<p> <strong>&bull; After 30 minutes in solution, greater than 99% of creatine remained available from the creatine monohydrate.</strong> </p>
<p> <strong>&bull; After 30 minutes in solution, only 73% of creatine from creatine ethyl ester remained available from one sample, and 62% remained available from another sample. </strong></p>
<p> <strong>&bull; After 120 minutes in solution, more than 99% of creatine remained available from creatine monohydrate (further evidence of the remarkable stability of creatine monohydrate, by the way).</strong> </p>
<p> <strong>&bull; After 120 minutes in solution, the two CEE samples tested showed 72% and 11% creatine available. </strong></p>
<p> <strong>&bull; Substantial creatinine formation (and not simply the dissociation of creatine from its ester) was noted in the CEE solutions.</strong> </p>
<p> <a href="http://www.npicenter.com/anm/templates/newsATemp.aspx?articleid=18806&zoneid=26" target="_blank">Article Link &#45; Creatine Efficacy Headlines At Sports Nutrition Meeting. </a></p>
<p> Admittedly, the research on the stability of CEE is preliminary, but it&#39;s clear that, at the very least, there are <strong><em>major</em></strong> differences between creatine ethyl ester and creatine monohydrate &#45; differences that do not bode well for the stability, safety, or effectiveness of creatine esters. The marketers of CEE seem to want to have their cake and eat it too. They want us to believe that CEE is <strong><em>different</em></strong> than creatine monohydrate when they tout its supposed benefits, but <strong><em>the same</em></strong> as creatine monohydrate when they attempt to assure us of its safety. Unfortunately for them, science simply doesn&#39;t work this way. </p>
<p> So, it should be recognized <strong><em>explicitly</em></strong> that, at this point in time, <strong><em>every</em></strong> known piece of scientific literature on creatine ethyl ester (<strong><em>including</em></strong> the literature submitted to the FDA by the products&#39; marketers &#45; to garner approval for CEE to be used in dietary supplements) showed that creatine ethyl ester degrades into creatinine at a markedly <strong><em>higher</em></strong> rate than creatine monohydrate &#45; in both <em>in vitro</em> and <em>in vivo</em> studies. </p>
<p> And to boot, <strong><em>zero</em></strong> studies at this point have been conducted to show that creatine ethyl ester is in any way effective for increasing creatine or phosphocreatine levels. Nor have any studies been conducted to show that creatine ethyl ester improves any marker of health, or mental/physical function. </p>
<p> Considering that there is no evidence to support the contention that creatine ethyl ester is in any way superior to creatine monohydrate, the only reasonable conclusion we can draw at this point is that those consuming creatine esters have been deceived. They are not only <strong><em>not</em></strong> reaping the full benefits of creatine, but they are, instead, likely to be consuming a mildly toxic substance. </p>
<p> One of the most frustrating things about debunking the fraudulent and unsubstantiated claims of the sports nutrition industry is that there seems to be a limitless amount of them. Every day, it seems, we&#39;re bombarded with one baseless claim after another; and, if we&#39;re not careful, we could spend all of our time deconstructing assertions so ridiculous, that they&#39;re not even open to legitimate scientific consideration in the first place. </p>
<p> To focus on the few (yet remarkably vocal) bad apples in the nutritional supplement industry, however, would ultimately be a disservice to the honest and hard&#45;working researchers who are exploring the novel health&#45;promoting actions of nutritional substances. At Integrated Supplements, we&#39;d much rather spend our time bringing their research to your attention than exposing the snake&#45;oil salesmen. </p>


</div><!--Close third Pane-->

    <div id="tab4">
    <div class="panevideo" style="display:block">
<iframe width="210" height="157" src="http://www.youtube.com/embed/h0F-OHgKY50" frameborder="0" allowfullscreen></iframe>
 </div><!--close panevideo-->
    <div class="panecolumn" style="display:block">
    <h2>Video: What is Creatine?</h2>

    </div><!--close panecolumn-->
   <div class="clear" style="display:block"></div>
    <hr />
    <h2>Integrated Supplements Audio Series</h2>
    <p><a href="http://www.integratedsupplements.com/intsup/intsup0014.audio">The Truth About Creatine</a></p>
    <hr />
    <h2>Creapure<sup>&reg;</sup> Creatine Articles</h2>
    <p><a href="http://integratedsupplements.typepad.com/integrated_supplements_bl/2010/01/creatine-a-possible-weapon-against-tinnitus-and-noiseinduced-hearing-loss.html" target="_blank">Creatine &#8212; A Possible Weapon Against Tinnitus And Noise-Induced Hearing Loss</a></p>
    <p><a href="http://integratedsupplements.typepad.com/integrated_supplements_bl/2009/12/yet-another-study-shows-creatine-ethyl-ester-to-be-a-useless-creatine-supplement.html" target="_blank">Yet Another Study Shows Creatine Ethyl Ester To Be A Useless Creatine Supplement</a></p>
    <p><a href="http://integratedsupplements.typepad.com/integrated_supplements_bl/2009/07/guanidinopropionic-acid-whats-in-your-creatine-product.html" target="_blank">Guanidinopropionic Acid &#8212; What&#39;s in Your Creatine Product?</a></p>
    <p><a href="http://integratedsupplements.typepad.com/integrated_supplements_bl/2009/01/the-dietary-supplement-creatine-has-risen-to-prominence-in-recent-decades-largely-because-of-its-effectiveness-in-helping.html" target="_blank">Study Shows Creatine Supplementation May Prevent Aging and Degeneration</a></p>
    <p><a href="http://integratedsupplements.typepad.com/integrated_supplements_bl/2008/12/study-finds-creatine-improves-health-and-increases-lifespan-in-mice.html" target="_blank">Study Finds Creatine Improves Health and Increases Lifespan in Mice</a></p>

    </div>
    <div id="tab5">
   <ul>
    <li><p><em>This is the best quality creatine I have tried. Very easy to mix dissolves instantly and has no taste at all. When you are going to buy a creatine product make sure it is a pure creapure the highest quality creatine their is and you will notice the difference once you start taking it.</em></p>
	<hr /> 
    <li><p><em> This is the best creatine product without a doubt. Integrated Supplements produce very high quality products and their committment to this can be seen in the ingredients they use. Firstly its made from Creapure which is a big plus and I didn&#39;t experience any issues with mixing. I use it in the morning on my non workout days and right after my workout. I take with their whey protein isolate and this combination has given me great results. My strength, stamina, and muscle size and definition, all have improved! So if you want a high quality creatine product that will deliver results, I reccommend this one by all means!</em></p>
    <hr /> 
    <li><p><em>The greatest results I have ever had from a creatine! I&#39;ve tried Ethyl Ester and it never worked for me at all, Creature I had some good results but nothing like this, I also take 100% Whey protein and since this combination that I started about 3 weeks ago I have put on 4 pounds, and have only gone up to a 9% body fat from an 8%. In my opinion it has to be Creapure Creatine.</em></p>
   <hr /> 
    <li><p><em>By far best creatine you can possibly buy although taste may not be a good factor in this product you can mix it with anything including your protein shake or mass gainer or just fruit i give this product a 10 for the results it has given me</em></p>
   <hr /> 
    <li><p><em>Creapure Creatine is the best creatine supplement available by far.  Many people look for convenience, or choose a supplement by reading magazines that tout the virtues of the newest product.  Many mimic the pros who are paid to say that the supplements that they use are the ones to use.  Do your own research, and do a trial usage of Creapure and see for yourself.  This product shows and proves its superiority.</em></p>
 <hr />    
    </li>
    </ul>
    </div><!--Close fifth Pane-->
</div>
</div><!--Close productbartabs -->